config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :knowledges

  root :to => "home#index"

end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
  belongs_to :user
  def get_user_name
    name = User.where(self.user_id).first.email
  end
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/app_config.yml"
  namespace Rails.env
  load! if Rails.env.development?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :knowledges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/knowledges_controller.rb
class KnowledgesController < ApplicationController
  before_action :set_knowledge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /knowledges
  # GET /knowledges.json
  def index
    @knowledges = Knowledge.all
  end

  # GET /knowledges/1
  # GET /knowledges/1.json
  def show
  end

  # GET /knowledges/new
  def new
    @knowledge = Knowledge.new
  end

  # GET /knowledges/1/edit
  def edit
  end

  # POST /knowledges
  # POST /knowledges.json
  def create
    @knowledge = Knowledge.new(knowledge_params)
    @knowledge.user = current_user
    respond_to do |format|
      if @knowledge.save
        format.html { redirect_to @knowledge, notice: 'Knowledge was successfully created.' }
        format.json { render :show, status: :created, location: @knowledge }
      else
        format.html { render :new }
        format.json { render json: @knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knowledges/1
  # PATCH/PUT /knowledges/1.json
  def update
    respond_to do |format|
      if @knowledge.update(knowledge_params)
        format.html { redirect_to @knowledge, notice: 'Knowledge was successfully updated.' }
        format.json { render :show, status: :ok, location: @knowledge }
      else
        format.html { render :edit }
        format.json { render json: @knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knowledges/1
  # DELETE /knowledges/1.json
  def destroy
    @knowledge.destroy
    respond_to do |format|
      format.html { redirect_to knowledges_url, notice: 'Knowledge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_knowledge
    @knowledge = Knowledge.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def knowledge_params
    params.require(:knowledge).permit(:pro_name, :skill_of_harvest, :lift_of_harvest, :study_plan, :hope_plan, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/knowledges_helper.rb
module KnowledgesHelper
end

app/views/home/index.html.erb
<div class="bs-glyphicons">
  <ul class="bs-glyphicons-list">
    <li>
      <span class="self_badge"></span>
      <a href="/knowledges/new"><span class="glyphicon-class">添加项目知识</span></a>
    </li>
  </ul>
</div>
<!-- 
  <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>To see the difference between static and fixed top navbars, just scroll.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
      </div>-->

app/views/knowledges/_form.html.erb
<fieldset>
  <section>
    <%= f.input :pro_name,:class=>"input"%>
    <%= error_span(@knowledge[:pro_name]) %>
  </section>
  <section>
    <label class="textarea">
      <%= f.input :skill_of_harvest,:rows=>"3" %>
      <%= error_span(@knowledge[:skill_of_harvest]) %>
    </label>
  </section>
  <section>
    <label class="textarea">
      <%= f.input :lift_of_harvest %>
      <%= error_span(@knowledge[:lift_of_harvest]) %>
    </label>
  </section>
  <section>
    <label class="textarea">
      <%= f.input :study_plan %>
      <%= error_span(@knowledge[:study_plan]) %>
    </label>
  </section>
  <section>
    <label class="textarea">
      <%= f.input :hope_plan %>
      <%= error_span(@knowledge[:hope_plan]) %>
    </label>
  </section>
</fieldset>
<footer>
  <%= f.button :submit, :class => 'btn-u btn-u-default'%>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                knowledges_path, :class => 'button btn-u btn-u-default' %>
</footer>

app/views/knowledges/edit.html.erb
<%- model_class = Knowledge -%>
<div class="tab-v1 margin-bottom-60">
  <div class="tab-content">
    <!-- Icons and Placeholders -->
    <div class="tab-pane fade in active" id="home-1">
      <%= simple_form_for @knowledge, :html => { :class => 'form-horizontal sky-form' } do |f| %>
        <header><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></header>
        <%= render :partial => 'form',:locals=>{:f=>f} %>
      <%end%>
    </div>
    <!-- End Icons and Placeholders -->
  </div>
</div>

app/views/knowledges/index.html.erb
<%- model_class = Knowledge -%>
<div class="col-md-12">
  <!--Basic Table-->
  <div class="panel panel-green margin-bottom-40">
    <div class="panel-heading" style="position:relative">
      <h3 class="panel-title"><i class="fa fa-tasks"></i> <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
      <%= link_to t('.new', :default => t("helpers.links.new")),
            new_knowledge_path,
            :class => 'btn btn-default',:style=>"position:absolute;top:1px;right:10px;color:#000" %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:pro_name) %></th>
          <th><%= model_class.human_attribute_name(:user_id) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @knowledges.each do |knowledge| %>
          <tr>
            <td><%= link_to knowledge.pro_name, knowledge_path(knowledge) %></td>
            <td><%= knowledge.get_user_name %></td>
            <td><%=l knowledge.created_at %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_knowledge_path(knowledge), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.show', :default => t("helpers.links.show")),
                      knowledge_path(knowledge), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      knowledge_path(knowledge),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <!--End Basic Table-->
</div>

app/views/knowledges/new.html.erb
<%- model_class = Knowledge -%>
<!-- Tabs -->
<div class="tab-v1 margin-bottom-60">
  <div class="tab-content">
    <!-- Icons and Placeholders -->
    <div class="tab-pane fade in active" id="home-1">
      <%= simple_form_for @knowledge, :html => { :class => 'form-horizontal sky-form' } do |f| %>
        <header><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></header>
        <%= render :partial => 'form',:locals=>{:f=>f} %>
      <%end%>
    </div>
    <!-- End Icons and Placeholders -->
  </div>
</div>
<!-- End Tabs -->

app/views/knowledges/show.html.erb
<%- model_class = Knowledge -%>
<div class="tab-v3 sky-form">
  <div class="page-header tab-content">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    <hr style="margin:10px">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:pro_name) %>:</strong></dt>
      <dd><%= @knowledge.pro_name %></dd>
      <br/>
      <dt><strong><%= model_class.human_attribute_name(:skill_of_harvest) %>:</strong></dt>
      <dd><%= @knowledge.skill_of_harvest %></dd>
      <br/>
      <dt><strong><%= model_class.human_attribute_name(:lift_of_harvest) %>:</strong></dt>
      <dd><%= @knowledge.lift_of_harvest %></dd>
      <br/>
      <dt><strong><%= model_class.human_attribute_name(:study_plan) %>:</strong></dt>
      <dd><%= @knowledge.study_plan %></dd>
      <br/>
      <dt><strong><%= model_class.human_attribute_name(:hope_plan) %>:</strong></dt>
      <dd><%= @knowledge.hope_plan %></dd>
      <br/>
      <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
      <dd><%= @knowledge.get_user_name %></dd>
    </dl>
    <footer style="padding:10px">
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              knowledge_path(@knowledge),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => ' btn btn-danger button',:style=>"background-color: #d9534f;" %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_knowledge_path(@knowledge), :class => 'button btn-u btn-u-default' %>
      <%= link_to t('.back', :default => t("helpers.links.back")),
              knowledges_path, :class => 'button btn-u btn-u-default'  %>
    </footer>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PksPro" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PKS-PRO</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/knowledges">项目</a></li>
            <!--<li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>-->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <!--<li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>-->
            <% if current_user %>
              <li><%= link_to('退出', destroy_user_session_path, :method => :delete) %></li>
              <li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
            <% else %>
              <li><%= link_to('注册', new_registration_path(:user)) %></li>
              <li><%= link_to('登录', new_session_path(:user)) %></li>
            <% end %>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <%= yield%>
    </div>
    <!-- /container -->
    <footer class="footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>
  </body>
</html>

app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PksPro" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PksPro</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>